### ISSUE TITLE
Reading from buffer can sometimes fail

### ISSUE THREAD

**Issue by Tezar** [justinmayhew/greenstalk#13] opened 2024-09-10 15:34 UTC
When parsing responses, the current implementation uses `_reader.read(size + 2)` to read a chunk of data. However, this method returns at most the specified number of bytes, not necessarily the exact amount. This can lead to incomplete reads, especially under high load or in asynchronous environments. I have found [the issue](https://github.com/koodaamo/aiostalk/issues/8) it while using async version aiostalk.

Would you be open for solution akin this?

```
def __read_bytes_from_reader(self, count: int) -> bytes:
    data = b''
    while len(data) < count:
        chunk = self._reader.read(count - len(data))
        if not chunk:
            raise EOFError(f"Unexpected end of stream. Expected {count} bytes, got {len(data)} bytes.")
        data += chunk
    return data

def _read_chunk(self, size: int) -> bytes:
    data = self.__read_bytes_from_reader(size + 2)
    return _parse_chunk(data, size)
```

**Comment by justinmayhew** [comment] 2024-09-14 11:55
I was not able to reproduce this issue. The file object returned from `socket.makefile("rb")` does block until the expected number of bytes are read (which was the original motivation for using that instead of calling `.recv()` directly on the socket).

This seems to be a problem specific to `aiostalk`, so I'm going to close this.

**Closed by justinmayhew** 2024-09-14 11:55 UTC

**Comment by Tezar** [comment] 2024-09-16 15:14
Thanks for looking into it. I have failed to realize that `_reader` in `greenstalk ` comes from makefile, hence it's file like object and the assumption for the read behaviour stands there. Tried to stress test it but looks like docs are on the point, everything works.

Sorry for the misleading report and thanks for making this lib!
